# Generated by Django 4.2 on 2024-10-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrapic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
