# Generated by Django 4.2 on 2024-10-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrapic', '0002_users_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='active_type',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='places',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddIndex(
            model_name='places',
            index=models.Index(fields=['name'], name='terrapic_pl_name_55c532_idx'),
        ),
        migrations.AddIndex(
            model_name='places',
            index=models.Index(fields=['location'], name='location_idx'),
        ),
    ]
