# Generated by Django 4.2 on 2024-10-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrapic', '0003_remove_posts_active_type_remove_posts_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='favolite_count',
            field=models.IntegerField(default=0),
        ),
    ]
