# Generated by Django 4.2 on 2024-10-18 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrapic', '0004_places_favolite_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='favolite_count',
        ),
        migrations.AlterField(
            model_name='favorites',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='terrapic.places'),
        ),
    ]
