# Generated by Django 4.2 on 2024-11-25 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrapic', '0006_posts_photo_spot_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='terrapic.places'),
        ),
    ]
