version: '3.9'

services:
  db:
    image: kartoza/postgis:14
    platform: linux/arm64
    environment:
      POSTGRES_DB: ${DB_NAME:-terrapic}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./terrapic_backend
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./terrapic_backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-terrapic}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-admin}
      - PYTHONPATH=/app
      - DJANGO_SETTINGS_MODULE=terrapic_backend.settings
      - GDAL_LIBRARY_PATH=/lib/aarch64-linux-gnu/libgdal.so
      - SECRET_KEY=${SECRET_KEY:-django-insecure-k=btg71b%^7yhz4#m#pu+%t2*b7mfj1&)fvr142q6+n*@6!#-c}
      - DEBUG=${DEBUG:-True}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1}
      - CORS_ALLOW_ALL_ORIGINS=${CORS_ALLOW_ALL_ORIGINS:-True}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-}
    depends_on:
      - db

volumes:
  postgres_data: